### ISSUE TITLE
BiKMi question: How to validate omics data with the covid19kg knowledge?

### ISSUE THREAD

**Issue by djinnome** [covid19kg/Analysis#3]
Hi folks,

Apologies for posting here, there was no obvious help link in BiKMi.

In your paper, you mentioned:

> Along  with the KG, we implemented a web application                   (https://bikmi.covid19-knowledgespace.de) for querying, browsing, and   navigating the KG (Figure1)  . The visualization enables users to explore  and query the network (e.g., filtering nodes or edges, or calculating paths between nodes of interest). Additionally, it enables users to upload omics data and validate its signals against the knowledge contained in the network. To demonstrate this feature, the web application is loaded with the transcriptomics experiments conducted by Blanco-Melo et al. (2020).

When I logged in to the [BiKMi dashboard](https://bikmi.covid19-knowledgespace.de/dashboard/) 
and click on Workspace, I see a place to upload "Differential Gene Expression Data", so I formatted  Supplementary table II from [Blanco-Melo et al](https://www.biorxiv.org/content/biorxiv/early/2020/03/24/2020.03.24.004655/DC2/embed/media-2.xlsx?download=true)  and successfully uploaded it to the workspace, but it isn't clear how to view this data in the context of the knowledge graph. 

Please advise!

Sincerely,

Jeremy

**Comment by YojanaGadiya** [comment]
To check the outcome of your gene expression data, you can always look below the outcome graph of your generated query in the "Query" section on the Dashboard. Try using the "Path" section in the Query.

Hope this helps!

**Comment by djinnome** [comment]
Hi @YojanaGadiya 

Thanks for responding. I think I understand now. If I put in  from:AGTR1 to:ACE in the "Path" query then I see  that the complex(AGTR1, angiotensin II) increases molecularActivity(ACE) and that Blanco-Melo data contradicts this knowledge since AGTR1 is upregulated and ACE is downregulated.
